# Generated by Django 4.0.5 on 2022-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('developmentMode', models.BooleanField()),
                ('supportEmail', models.EmailField(max_length=254)),
                ('noReplyEmail', models.EmailField(max_length=254)),
                ('developerEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
