# Generated by Django 4.0.5 on 2022-06-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
