# Generated by Django 4.0.5 on 2022-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites_api', '0002_alter_website_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='timezone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
